<?php
/** @var \IdeaInYou\StoreLocator\Block\Hello $block */
$block->createStoreLocator();
$collection = $block->getStoreLocatorCollection()->getItems();
?>
<h1>asdasda</h1>
<h1><?= $block->getHelloMessage() ?></h1>
<table>
    <td>entity_id</td>
    <td>store Name</td>
    <td>latitude</td>
    <td>longitude</td>
    <td>time Open</td>
    <td>time Close</td>
    <td>comment</td>
    <td>product id</td>
<?php foreach ($collection as $item): ?>
    <tr>
        <td><?= $item->getData('entity_id'); ?></td>
        <td><?= $item->getData('storeName'); ?></td>
        <td><?= $item->getData('latitude'); ?></td>
        <td><?= $item->getData('longitude'); ?></td>
        <td><?= $item->getData('timeOpen'); ?></td>
        <td><?= $item->getData('timeClose'); ?></td>
        <td><?= $item->getData('comment'); ?></td>
        <td><?= $item->getData('product_id'); ?></td>
    </tr>
<?php endforeach ?>
</table>
<?php
    var_dump($block->getStoreLocatorById(1)->getData());
?>
