<?php
/** @var \IdeaInYou\StoreLocator\Block\Store $block */
$block->createStoreLocator();
$collection = $block->getStoreLocatorCollection()->getItems();
?>

<table id="mapTable">
    <tr class="tableHead">
        <td>entity_id</td>
        <td>store Name</td>
        <td>description</td>
        <td>country</td>
        <td>state</td>
        <td>city</td>
        <td>address</td>
        <td>post</td>
        <td>latitude</td>
        <td>longitude</td>
    </tr>


    <?php foreach ($collection as $item): ?>
        <tr class="mapZoom"
            data-latitude ='<?= $item->getData('latitude'); ?>'
            data-longitude ='<?= $item->getData('longitude'); ?>'
        >
            <td><?= $item->getData('entity_id'); ?></td>
            <td><?= $item->getData('storeName'); ?></td>
            <td><?= $item->getData('description'); ?></td>
            <td><?= $item->getData('country'); ?></td>
            <td><?= $item->getData('state'); ?></td>
            <td><?= $item->getData('city'); ?></td>
            <td><?= $item->getData('address'); ?></td>
            <td><?= $item->getData('post'); ?></td>
            <td><?= $item->getData('latitude'); ?></td>
            <td><?= $item->getData('longitude'); ?></td>
        </tr>
    <?php endforeach ?>



</table>
