<?php
/** @var \IdeaInYou\StoreLocator\Block\Store $block */
$block->createStoreLocator();
$collection = $block->getStoreLocatorCollection()->getItems();
?>

<table id="mapTable">
    <tr class="tableHead">
        <td>store Name</td>
        <td>description</td>
        <td>country</td>
        <td>state</td>
        <td>city</td>
        <td>address</td>
        <td>post</td>
        <td>latitude</td>
        <td>longitude</td>
    </tr>


    <?php foreach ($collection as $item): ?>
        <tr class='mapZoom'
            data-latitude ='<?= $item->getData('latitude'); ?>'
            data-longitude ='<?= $item->getData('longitude'); ?>'
        >
            <td class='storeName'><?= $item->getData('storeName'); ?></td>
            <td class='description'><?= $item->getData('description'); ?></td>
            <td class='country'><?= $item->getData('country'); ?></td>
            <td class='state'><?= $item->getData('state'); ?></td>
            <td class='city'><?= $item->getData('city'); ?></td>
            <td class='address'><?= $item->getData('address'); ?></td>
            <td class='post'><?= $item->getData('post'); ?></td>
            <td class='latitude'><?= $item->getData('latitude'); ?></td>
            <td class='longitude'><?= $item->getData('longitude'); ?></td>
        </tr>
    <?php endforeach ?>
</table>
