<?php
/** @var \IdeaInYou\StoreLocator\Block\Store $block */
$block->createStoreLocator();
$collection = $block->getStoreLocatorCollection()->getItems();
?>


<?php
$i =0;
$storeArr = [];
foreach ($collection as $item):
    $i += 1;
    $storeArr[$i] = [
        $item->getData('entity_id'),
        $item->getData('storeName') . ' ' . $item->getData('description')
    ];
endforeach;
?>


<?php
$locations = [];
$i = 0;
foreach ($collection as $item):
    $locations[$i]['lat'] = +$item->getData('latitude');
    $locations[$i]['lng'] = +$item->getData('longitude');
    $i +=1;
endforeach;
?>

<script type="text/x-magento-init">
    {
        "*": {
            "storeLocatorForm": {
                "formSelector": "#storeLocatorForm",
                "submitUrl": "<?= $block->getUrl('ideaInYou_storeLocator/ajax/save') ?>",
                "messageSelector": "#addReviewMessage"
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
        "*": {
        "storeLocatorMap": {
                "mapMessage": "hello",
                "mapTitle": <?= json_encode($storeArr); ?>,
                "locations": <?= json_encode($locations) ?>
            }
        }
    }
</script>
